config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get "/dashboard" => "dashboard#index"
  get "/dashboard/attacks_per_day" => "dashboard#attacks_per_day"
  resources :uploads, only: [:index, :create]
  get "/manage_users" => "users#index"

  get '/create_users' => 'users#add_user'
  post '/create_users' => 'users#create'

  get '/user_profile' => 'users#profile'
  patch '/update_profile' => 'users#update_profile'
  delete '/delete_user' => 'users#delete_user'

  get "/attacks" => "attacks#index"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :uploads, dependent: :destroy
  scope :by_id, -> id { where(id: id) }
  scope :by_name, -> name { where('first_name ilike ? OR last_name ilike ?', "%#{name}%", "%#{name}%") }
  scope :by_role, -> role { role == 'true' ? where(admin: true) : where(admin: false).or(where(admin: nil))  }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # Scopes
  has_scope :by_id
  has_scope :by_name
  has_scope :by_role

  def index
    redirect_to root_path unless current_user&.admin?
    @users = apply_scopes(User).order(created_at: :desc).all
  end

  def add_user
    @user = User.new
  end

  def create
    redirect_to root_path unless current_user&.admin?
    user = User.new(user_params)
    if user.save
      # display success
      flash[:notice] = "User was successfully created."
    else
      # display error
      flash[:alert] = "User was not created. Errors: " + user.errors.full_messages.join(',')
    end
    redirect_to manage_users_path
  end

  def profile
    @user = current_user
  end

  def update_profile
    update_params = user_params.to_h
    update_params.delete('password') if update_params['password'].blank?
    update_params.delete('password_confirmation') if update_params['password_confirmation'].blank?

    if current_user.update(update_params)
      # display success
      flash[:notice] = "Date was successfully updated."
    else
      # display error
      flash.now[:alert] = "Date was not updated. Errors: " + current_user.errors.full_messages.join(',')
    end
    redirect_to user_profile_path
  end

  def delete_user
    User.find(params[:id]).destroy!
    redirect_to manage_users_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add_user.html.erb
<div id="wrapper">
  <%= render 'shared/header' %>
    <div id="main">
      <section class="main">
        <header class="major">
          <h2>Add User</h2>
        </header>
        <%= form_for @user, url: create_users_path do |f| %>
          <div class="row gtr-uniform">
              <div class="field col-6 col-12-xsmall">
              <%= f.label :First_name %><br />
              <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
            </div>

            <div class="field col-6 col-12-xsmall">
              <%= f.label :Last_name %><br />
              <%= f.text_field :last_name, autofocus: true, autocomplete: "Last_name" %>
            </div>

            <div class="field col-12">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
            </div>

            <div class="field col-12">
              <%= f.label :password %>
              <em>(6 characters minimum)</em>
              <%= f.password_field :password, autocomplete: "new-password" %>
            </div>

            <div class="field col-12">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
            </div>

            <div class="actions">
              <%= f.submit "Add", :class=> "button primary" %>
            </div>
          </div>
        <% end %>
    </section>
  </div>
</div>

app/views/users/index.html.erb
<div id="wrapper">
  <%= render 'shared/header' %>
  <div id="main">
    <section class="main">
      <header class="major">
        <h2>Users</h2>
      </header>
      <%= form_with url: "/manage_users", method: :get do |f| %>
        <%= f.text_field :by_id, value: params[:by_id], placeholder: 'ID...', class: 'col-3 col-12-xsmall filters' %>
        <%= f.text_field :by_name, value: params[:by_name], placeholder: 'Name...', class: 'col-3 col-12-xsmall filters' %>
        <%= f.select :by_role, options_for_select([['User', 'false'], ['Admin', 'true']], params[:by_role]), { prompt: 'User Role...' }, { class: 'col-3 col-12-xsmall filters' } %>
        <%= f.submit "Search", class: 'button primary filters col-3', disable_with: 'Submiting...' %>
      <% end %>

      <div class="table-wrapper">
        <table class="alt">
          <thead>
            <tr>
              <th>ID</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Role</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.id %></td>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= user.admin? ? 'Admin' : 'User' %></td>
                <td><%= link_to 'delete', delete_user_path(id: user.id), method: :delete %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="actions">
            <%= link_to "Add User", create_users_path, :class=> "button primary" %>
            </div>
      </div>
    </section>
  </div>
</div>

app/views/users/profile.html.erb
<div id="wrapper">
  <%= render 'shared/header' %>
    <div id="main">
      <section class="main">
        <header class="major">
          <h2>Update Profile</h2>
        </header>
        <%= form_for @user, url: update_profile_path do |f| %>
          <div class="row gtr-uniform">
              <div class="field col-6 col-12-xsmall">
              <%= f.label :First_name %><br />
              <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
            </div>

            <div class="field col-6 col-12-xsmall">
              <%= f.label :Last_name %><br />
              <%= f.text_field :last_name, autofocus: true, autocomplete: "Last_name" %>
            </div>

            <div class="field col-12">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
            </div>

            <div class="field col-12">
              <%= f.label :password %>
              <em>(6 characters minimum)</em>
              <%= f.password_field :password, autocomplete: "new-password" %>
            </div>

            <div class="field col-12">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
            </div>

            <div class="actions">
              <%= f.submit "Update", :class=> "button primary" %>
            </div>
          </div>
        <% end %>
    </section>
  </div>
</div>