config/routes.rb
# require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get "/dashboard" => "dashboard#index"
  get "/dashboard/attacks_per_day" => "dashboard#attacks_per_day"
  resources :uploads, only: [:index, :create]
  get "/manage_users" => "users#index"

  get '/create_users' => 'users#add_user'
  post '/create_users' => 'users#create'

  get '/user_profile' => 'users#profile'
  patch '/update_profile' => 'users#update_profile'
  delete '/delete_user' => 'users#delete_user'

  get "/attacks" => "attacks#index"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end
end

app/views/shared/_footer.html.erb
<div id="wrapper">
<!-- Footer -->
  <footer id="footer">
    <section>
      <h2>DIoTA</h2>
      <p>Smart City is the most experienced and flexible provider of infrastructure, technology,
        and telecommunications facilities for convention centers, companies, and entertainment venues,
        and towards achieving a secure smart city, we aspires to contribute to help meet this challenge,
        by introducing a system that can detect malicious attacks using deep and machine learning techniques.</p>
    </section>
    <section>
      <h2>Find Us</h2>
      <dl class="alt">
        <dt>Address</dt>
        <dd>Medina, Taibah University</dd>
        <dt>Email</dt>
        <dd><a href="#">Diota.sau@gmail.com</a></dd>
      </dl>
    </section>
    <p class="copyright">&copy; DIoTA, 2021.</p>
  </footer>
</div>

app/views/shared/_header.html.erb
<!-- Header -->
<nav id="nav" class="alt">
	<ul>
		<li style= "margin-right:30%"><%= image_tag "LOGO-REP1.png", class: "logo" %><li>
		<li style= "margin-left:15%"><a href="<%= root_path %>" >Home</a></li>
		<%= render 'shared/user_dropdown' %>
	</ul>
</nav>

app/views/shared/_user_dropdown.html.erb
<% if current_user %>
  <li>
    <div class="dropdown">
      <a class= 'button'>
        Hi <%= current_user.first_name%>
        <img src="https://img.icons8.com/ios/16/000000/down-squared--v1.png"/>
      </a>
      <div class="dropdown-content">
      <%= link_to 'Profile', user_profile_path, class: 'dropbtn' %>
      <%= link_to 'Logout', destroy_user_session_path, class: 'dropbtn', method: :delete %>
      </div>
    </div>
  </li>
<% else %>
  <li><div class="dropdown">
    <%= link_to user_session_path, class: 'button' do %>
      LOGIN
    <% end %>
  </div> </li>
<% end %>